name: pakvpnn
version: '1.0.0'
description: PAK VPN Flutter app

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/datasecurity.png
    - assets/securelogin.png
    - assets/dataprivacy.png
    - assets/pakistan.png
    - assets/uae.png
    - assets/malaysia.png
